---
title: "RWorksheet#5b"
author: "Condag, Gagante, and Gonzaga"
date: "2024-11-20"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Extracting 10 Products for each category from Amazon
```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(stringr)

url <- "https://www.amazon.com/"
session <- bow(url, 
               user_agent = "Educational")
session

urls <- c('https://www.amazon.com/s?k=shoes&crid=38ZJ8F21Z8HC3&sprefix=shoes%2Caps%2C453&ref=nb_sb_noss_1', 
          'https://www.amazon.com/s?k=makeup&crid=JKZ76XNFYQIR&sprefix=makeup%2Caps%2C478&ref=nb_sb_noss_1',
          'https://www.amazon.com/s?k=jewelry&crid=32NP062DSNN6S&sprefix=jewel%2Caps%2C479&ref=nb_sb_noss_2',
          'https://www.amazon.com/s?k=girl%27s+clothing&crid=24XOJPYVS1TSP&sprefix=girl%27s+clothing%2Caps%2C408&ref=nb_sb_noss_1',
          'https://www.amazon.com/s?k=babytoys&crid=32QK3FKF2G833&sprefix=babytoys%2Caps%2C511&ref=nb_sb_noss_2')

```

```{r}
library(rvest)

shoes <- read_html(urls[1]) %>%
  html_nodes("a.a-link-normal.s-underline-text.s-underline-link-text.s-link-style.a-text-normal") %>%
  html_attr("href") %>%
  unique() %>%
  paste0("https://www.amazon.com", .)

makeup <- read_html(urls[2]) %>%
  html_nodes("a.a-link-normal.s-underline-text.s-underline-link-text.s-link-style.a-text-normal") %>%
  html_attr("href") %>%
  unique() %>%
  paste0("https://www.amazon.com", .)

jewelry <- read_html(urls[3]) %>%
  html_nodes("a.a-link-normal.s-underline-text.s-underline-link-text.s-link-style.a-text-normal") %>%
  html_attr("href") %>%
  unique() %>%
  paste0("https://www.amazon.com", .)

girls_clothing <- read_html(urls[4]) %>%
  html_nodes("a.a-link-normal.s-underline-text.s-underline-link-text.s-link-style.a-text-normal") %>%
  html_attr("href") %>%
  unique() %>%
  paste0("https://www.amazon.com", .)

babytoys <- read_html(urls[5]) %>%
  html_nodes("a.a-link-normal.s-underline-text.s-underline-link-text.s-link-style.a-text-normal") %>%
  html_attr("href") %>%
  unique() %>%
  paste0("https://www.amazon.com", .)

product_category <- data.frame(
  Shoes = head(shoes, 10),
  Makeup = head(makeup, 10),
  Jewelry = head(jewelry, 10),
  Girls_Clothing = head(girls_clothing, 10),
  BabyToys = head(babytoys, 10)
)
```
```{r}
shoes_products <- product_category$Shoes
makeup_products<- product_category$Makeup
jewelry_products <- product_category$Jewelry
gc_products <- product_category$Girls_Clothing
bt_products <- product_category$BabyToys
```

```{r}
scrape_reviews <- function(url) {
  page <- read_html(url)
          
  product_name <- page %>%
    html_nodes(".a-size-large.product-title-word-break") %>%
    html_text(trim = T) %>%
    strsplit(" ") %>%                
    .[[1]] %>%                       
    .[1:4] %>%
    gsub("\\,", "", .) %>%
    paste(collapse = " ")  

  user_name_reviews <- page %>%
    html_nodes(".a-profile-name") %>%
    html_text() %>%
    unique()

  review_dates <- page %>%
    html_nodes(".a-size-base.a-color-secondary.review-date") %>%
    html_text() %>%
    gsub(".*on ", "", .)

  reviewer_rating <- page %>%
    html_nodes(".a-icon-alt") %>%
    html_text() %>%
    gsub(" out.*", "", .) %>%
    .[grepl("^[0-9.]+$", .)] %>% 
    as.numeric()

  review_title <- page %>%
    html_nodes(".a-size-base.a-link-normal.review-title.a-color-base.review-title-content.a-text-bold span:nth-of-type(2)") %>%
    html_text()

  text_reviews <- page %>%
    html_nodes(".a-expander-content.reviewText.review-text-content.a-expander-partial-collapse-content") %>%
    html_text(trim = TRUE)
    
  data.frame(
    Product_Name = rep(product_name, 20),
    Reviewer_Names = user_name_reviews[2:21],
    Review_Date = review_dates[1:20],
    Individual_Ratings = reviewer_rating[1:20],
    Review_Title = review_title[1:20],
    Text_Reviews = text_reviews[1:20]
    )
}

shoes_reviews <- lapply(shoes_products, scrape_reviews)
makeup_reviews <- lapply(makeup_products, scrape_reviews)
jewelry_reviews <- lapply(jewelry_products, scrape_reviews)
gc_reviews <- lapply(gc_products, scrape_reviews)
bt_reviews <- lapply(bt_products, scrape_reviews)
```

```{r}
shoes_reviews_df <- do.call(rbind, shoes_reviews)
makeup_reviews_df <- do.call(rbind, makeup_reviews)
jewelry_reviews_df <- do.call(rbind, jewelry_reviews)
gc_reviews_df <- do.call(rbind, gc_reviews)
bt_reviews_df <- do.call(rbind, bt_reviews)

```

```{r}
print(shoes_reviews_df)
print(makeup_reviews_df)
print(jewelry_reviews_df)
print(gc_reviews_df)
print(bt_reviews_df)
```
